### ISSUE TITLE
Compiled version?

### ISSUE THREAD

**Issue by grahampugh** [brodjieski/profiles_parser#1]
Hi there, this script is awesome, but I've found issues running the raw script on some computers due to the version of the Xcode CL Tools installed. On the python version of this script it mentions that there is a compiled version available. Do you have that, or instructions on how to make it? 🙇

**Comment by brodjieski** [comment]
Hello!
The swift version here is meant to be run using the `swift` binary.. similar to a python script, but just written in swift. However, I think the current state is not 100% functional, and something I haven't visited in a bit.  So as it is now, it probably doesn't work?  I'll try to get this working at some point in the future... I did make a fix to the python script that may help in your case... let me know how that works.
